name: Tests builder

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"
      - "concentrated-liquidity-main"
      - "v[0-9]**"
  workflow_dispatch:

jobs:
  e2e-builder:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      -
        name: Build e2e image
        uses: docker/build-push-action@v3
        with:
          load: true
          context: .
          tags: osmosis:debug
          # Use experimental Cache backend API: https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#cache-backend-api
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BASE_IMG_TAG=debug
        if: env.GIT_DIFF
