name: Tests builder

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"
      - "concentrated-liquidity-main"
      - "v[0-9]**"
  workflow_dispatch:

jobs:
  e2e-builder:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      -
        name: Setup Go
        uses: actions/setup-go@v2.2.0
        with:
          go-version: 1.18
      -
        name: Check out repository code
        uses: actions/checkout@v2
      -
        name: Get git diff
        uses: technote-space/get-diff-action@v6.0.1
        with:
          PATTERNS: |
            **/**.wasm
            **/**!(test).go
            tests/**/**.go
            go.mod
            go.sum
            Makefile
      -
        name: Get data from build cache
        uses: actions/cache@v2
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          # * Build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~\AppData\Local\go-build
          key: ${{ runner.os }}-go-docker-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-docker-${{ matrix.go-version }}-
        if: env.GIT_DIFF
      -
        name: Build e2e image
        uses: docker/build-push-action@v3
        with:
          load: true
          context: .
          tags: osmosis:debug
          # Use experimental Cache backend API: https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#cache-backend-api
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/myimage.tar
          build-args: |
            BASE_IMG_TAG=debug
        if: env.GIT_DIFF
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: myimage
          path: /tmp/myimage.tar