name: Tests

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"
      - "concentrated-liquidity-main"
      - "v[0-9]**"
  workflow_dispatch:

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out repository code
        uses: actions/checkout@v2
      -
        name: Setup Golang
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.18
      -
        name: Display go version
        run: go version
      -
        name: Get data from build cache
        uses: actions/cache@v2
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          # * Build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~\AppData\Local\go-build
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-
      -
        name: Run unit tests
        run: make test-unit
  
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      -
        name: Setup Go
        uses: actions/setup-go@v2.2.0
        with:
          go-version: 1.18
      -
        name: Check out repository code
        uses: actions/checkout@v2
      -
        name: Get git diff
        uses: technote-space/get-diff-action@v6.0.1
        with:
          PATTERNS: |
            **/**.wasm
            **/**!(test).go
            tests/**/**.go
            go.mod
            go.sum
            Makefile
      -
        name: Get data from build cache
        uses: actions/cache@v2
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          # * Build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~\AppData\Local\go-build
          key: ${{ runner.os }}-go-docker-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-docker-${{ matrix.go-version }}-
        if: env.GIT_DIFF
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: env.GIT_DIFF
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: env.GIT_DIFF
      - name: Test e2e and Upgrade
        uses: BerniWittmann/background-server-action@1.0.4
        with:
          command: make test-e2e-ci
          start: make docker-build-debug
